import 'dart:io';

void main(List<String> args) {
  final force = args.contains('--force');
  final env = Platform.environment;

  _ensureFile(
    path: 'assets/env/.env.dev',
    force: force,
    content: _buildEnvContent(
      baseUrl: env['BASE_URL'] ?? 'https://api.dev.yourdomain.com/v1/',
      authBaseUrl:
          env['AUTH_BASE_URL'] ?? 'https://auth.dev.yourdomain.com/v1/',
      userBaseUrl:
          env['USER_BASE_URL'] ?? 'https://user.dev.yourdomain.com/v1/',
      firebaseApiKey: env['FIREBASE_API_KEY'] ?? 'YOUR_FIREBASE_API_KEY',
      googleMapsApiKey:
          env['GOOGLE_MAPS_API_KEY'] ?? 'YOUR_GOOGLE_MAPS_API_KEY',
    ),
  );

  _ensureFile(
    path: 'assets/env/.env.prod',
    force: force,
    content: _buildEnvContent(
      baseUrl: env['BASE_URL'] ?? 'https://api.prod.yourdomain.com/v1/',
      authBaseUrl:
          env['AUTH_BASE_URL'] ?? 'https://auth.prod.yourdomain.com/v1/',
      userBaseUrl:
          env['USER_BASE_URL'] ?? 'https://user.prod.yourdomain.com/v1/',
      firebaseApiKey: env['FIREBASE_API_KEY'] ?? 'YOUR_FIREBASE_API_KEY',
      googleMapsApiKey:
          env['GOOGLE_MAPS_API_KEY'] ?? 'YOUR_GOOGLE_MAPS_API_KEY',
    ),
  );

  _ensureFile(
    path: 'lib/firebase_options.dart',
    force: force,
    content: _buildFirebaseOptionsContent(env),
  );

  stdout.writeln('\nBootstrap completed.');
}

void _ensureFile({
  required String path,
  required bool force,
  required String content,
}) {
  final file = File(path);
  if (file.existsSync() && !force) {
    stdout.writeln('Skipped existing file: $path');
    return;
  }

  file.parent.createSync(recursive: true);
  file.writeAsStringSync(content);
  stdout.writeln('${file.existsSync() ? 'Wrote' : 'Created'} file: $path');
}

String _buildEnvContent({
  required String baseUrl,
  required String authBaseUrl,
  required String userBaseUrl,
  required String firebaseApiKey,
  required String googleMapsApiKey,
}) {
  return '''# Generated by tools/bootstrap_local.dart

# BASE_URL
BASE_URL=$baseUrl
AUTH_BASE_URL=$authBaseUrl
USER_BASE_URL=$userBaseUrl

# API Keys
FIREBASE_API_KEY=$firebaseApiKey
GOOGLE_MAPS_API_KEY=$googleMapsApiKey
''';
}

String _buildFirebaseOptionsContent(Map<String, String> env) {
  final apiKey = env['FIREBASE_API_KEY'] ?? 'YOUR_FIREBASE_API_KEY';
  final appId = env['FIREBASE_APP_ID'] ?? 'YOUR_FIREBASE_APP_ID';
  final senderId =
      env['FIREBASE_MESSAGING_SENDER_ID'] ??
      'YOUR_FIREBASE_MESSAGING_SENDER_ID';
  final projectId = env['FIREBASE_PROJECT_ID'] ?? 'YOUR_FIREBASE_PROJECT_ID';
  final storageBucket =
      env['FIREBASE_STORAGE_BUCKET'] ?? 'YOUR_FIREBASE_STORAGE_BUCKET';

  return '''// Generated by tools/bootstrap_local.dart.
// Replace placeholder values with your Firebase project settings if needed.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Firebase options have not been configured for web.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase options are only configured for Android by bootstrap.',
        );
      default:
        throw UnsupportedError(
          'Firebase options are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '$apiKey',
    appId: '$appId',
    messagingSenderId: '$senderId',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
  );
}
''';
}
